/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jni_HelloJNI */

#ifndef _Included_jni_HelloJNI
#define _Included_jni_HelloJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jni_HelloJNI
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jni_HelloJNI_sayHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
